# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: aufgaben
version: '1.7.2'
author: Oliver Kreischer
supportpage: github.com/olien/aufgaben/issues

page:
    title: 'Aufgaben'
    perm: aufgaben[]
    # block: system
    icon: rex-icon fa-calendar-check-o
    subpages:
        aufgaben: { title: 'Aufgaben',perm: aufgaben[] }
        kategorien: { title: 'Kategorien', perm: aufgaben[kategorien]}
