# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: aufgaben
version: '1.9.3'
author: Oliver Kreischer
supportpage: github.com/olien/aufgaben/issues

page:
  title: 'Aufgaben'
  perm: aufgaben[]
  pjax: true
  icon: rex-icon fa-calendar-check-o
  subpages:
      aufgaben: { title: 'Aufgaben',perm: aufgaben[] }
      kategorien: { title: 'Kategorien', perm: aufgaben[kategorien]}
      info:
        title: 'Info'
        subpages:
          hilfe: { title: 'Hilfe'}
          changelog: { title: 'Changelog'}
          lizenz: { title: 'Lizenz'}

requires:
    packages:
        phpmailer: '^2.0.1'
    redaxo: '>=5.0.0'
