# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: aufgaben
version: '4.1.1'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/aufgaben
info: Idee und Realisierung der ersten Version concedra.de / Oliver Kreischer
compile: 0

page:
  title: 'Aufgaben'
  perm: aufgaben[]
  pjax: true
  icon: rex-icon fa-calendar-check-o

requires:
    packages:
        be_style: '^2.1.0'
        phpmailer: '^2.0.1'
    redaxo: '>=5.2.0'
