# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: aufgaben
version: '2.0'
author: Oliver Kreischer
supportpage: www.redaxo.org/de/forum/
compile: 1

page:
  title: 'Aufgaben'
  perm: aufgaben[]
  pjax: true
  icon: rex-icon fa-calendar-check-o
  subpages:
      aufgaben: { title: 'Aufgaben',perm: aufgaben[] }
      kategorien: { title: 'Kategorien', perm: aufgaben[kategorien]}
      info:
        title: 'Info'
        subpages:
          hilfe: { title: 'Hilfe'}
          changelog: { title: 'Changelog'}
          lizenz: { title: 'Lizenz'}

requires:
    packages:
        be_style: '^2.1.0'
        phpmailer: '^2.0.1'
    redaxo: '>=5.1.0'
