
DROP TABLE IF EXISTS `%TABLE_PREFIX%aufgaben`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%aufgaben_categories`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%aufgaben_status`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%aufgaben_filter`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%aufgaben_user_settings`;

